---
- name: Install Docker & make sure it's enabled
  hosts: servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Start & Enable docker 
      service:
        name: docker
        state: started
        enabled: yes
  
